apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels: 
    component: cart
    project: roboshop
    tier: backend
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
    # deployment labels
  labels:
    component: cart
    project: roboshop
    tier: backend
spec:
  replicas: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels then only replicas will created
  selector:
    matchLabels:
      component: cart
      project: roboshop
      tier: backend
  # This is pod definition
  template:
    metadata:
      # Pod labels
      labels:
        component: cart
        project: roboshop
        tier: backend
    spec: 
      containers:
      - name: cart
        image: gsurendhar/cart:v2
        envFrom:
        - configMapRef:
            name: cart
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20 # if avg CPU utilization is more than 20, pods can be increased up to max of 5
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: backend    
spec:
  # These are the labels is use attach pod to service, this should exactly match pod labels then only pods are attached to service
  selector: 
    component: cart
    project: roboshop
    tier: backend
  ports:
  - protocol: TCP
    port: 8080   # service port
    targetPort: 8080    # container port
