apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels: 
    component: user
    project: roboshop
    tier: backend
data: 
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/user"
  REDIS_URL: "redis://redis:6379"   
---
apiVersion: app/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
    # deployment labels
  labels:
    component: user
    project: roboshop
    tier: backend
spec:
  replicaset: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels then only replicas will created
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: backend
  # This is pod definition
  template:
    metadata:
      # Pod labels
      labels:
        component: user
        project: roboshop
        tier: backend
    spec: 
      containers:
      - name: user
        image: gsurendhar/user:v2
        envFrom:
        - configMapRef:
            name: user
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20 # if avg CPU utilization is more than 20, pods can be increased up to max of 5
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: backend    
spec:
  # These are the labels is use attach pod to service, this should exactly match pod labels then only pods are attached to service
  selector: 
    component: user
    project: roboshop
    tier: backend
  ports:
    protocol: "TCP"
    port: 8080   # service port
    targetPort: 8080    # container port
